# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//tools/build_defs/testing:bzl_library.bzl", "bzl_library")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

cc_library(
    name = "status",
    srcs = [
        "status.cc",
    ],
    hdrs = [
        "status.h",
    ],
    deps = [
        "@abseil-cpp//absl/base:core_headers",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:cord",
    ],
)

cc_library(
    name = "proto_matchers",
    testonly = True,
    hdrs = ["proto_matchers.h"],
    deps = [
        ":proto",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:absl_log",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest",
        "@protobuf",
    ],
)

cc_test(
    name = "proto_matchers_test",
    srcs = ["proto_matchers_test.cc"],
    deps = [
        ":proto_matchers",
        ":proto_test_cc_proto",
        ":testing",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "status_matchers",
    testonly = True,
    hdrs = ["status_matchers.h"],
    deps = [
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@googletest//:gtest",
    ],
)

cc_test(
    name = "status_matchers_test",
    srcs = ["status_matchers_test.cc"],
    deps = [
        ":status_matchers",
        "@abseil-cpp//absl/memory",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "testing",
    testonly = True,
    srcs = ["testing.cc"],
    hdrs = ["testing.h"],
    deps = [
        ":proto",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "testing_test",
    srcs = ["testing_test.cc"],
    deps = [
        ":testing",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "collections",
    hdrs = [
        "collections.h",
    ],
    deps = [
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@protobuf",
    ],
)

cc_library(
    name = "proto",
    srcs = [
        "proto.cc",
    ],
    hdrs = [
        "proto.h",
    ],
    deps = [
        ":proto_string_error_collector",
        ":status",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@protobuf",
    ],
)

cc_library(
    name = "overload",
    hdrs = ["overload.h"],
)

cc_library(
    name = "io",
    srcs = [
        "io.cc",
    ],
    hdrs = [
        "io.h",
    ],
    deps = [
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings:str_format",
    ],
)

cc_test(
    name = "io_test",
    srcs = [
        "io_test.cc",
    ],
    deps = [
        ":io",
        ":status_matchers",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "ordered_map",
    hdrs = [
        "ordered_map.h",
    ],
    deps = [
        "@abseil-cpp//absl/container:btree",
    ],
)

cc_test(
    name = "collections_test",
    srcs = ["collections_test.cc"],
    deps = [
        ":collections",
        ":status_matchers",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "proto_test",
    srcs = ["proto_test.cc"],
    deps = [
        ":proto",
        ":proto_matchers",
        ":proto_test_cc_proto",
        ":status",
        ":status_matchers",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest_main",
    ],
)

proto_library(
    name = "proto_test_proto",
    srcs = ["proto_test.proto"],
)

proto_library(
    name = "test_artifact_writer_test_proto",
    srcs = ["test_artifact_writer_test.proto"],
)

cc_proto_library(
    name = "test_artifact_writer_test_cc_proto",
    deps = [":test_artifact_writer_test_proto"],
)

cc_proto_library(
    name = "proto_test_cc_proto",
    deps = [":proto_test_proto"],
)

cc_library(
    name = "version",
    srcs = ["version.cc"],
    hdrs = ["version.h"],
    deps = [
        ":status",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@re2",
    ],
)

cc_test(
    name = "version_test",
    srcs = ["version_test.cc"],
    deps = [
        ":status_matchers",
        ":version",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "syslog_sink",
    srcs = ["syslog_sink.cc"],
    hdrs = ["syslog_sink.h"],
    deps = [
        "@abseil-cpp//absl/log:log_entry",
        "@abseil-cpp//absl/log:log_sink",
        "@abseil-cpp//absl/log:log_sink_registry",
    ],
)

cc_library(
    name = "proto_string_error_collector",
    hdrs = ["proto_string_error_collector.h"],
    deps = [
        "@abseil-cpp//absl/strings",
        "@protobuf",
    ],
)

cc_library(
    name = "test_artifact_writer",
    testonly = True,
    srcs = ["test_artifact_writer.cc"],
    hdrs = ["test_artifact_writer.h"],
    deps = [
        ":proto",
        ":status",
        "@abseil-cpp//absl/base:core_headers",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/synchronization",
        "@googletest//:gtest",
        "@protobuf",
    ],
)

cc_library(
    name = "proto_ordering",
    testonly = True,
    srcs = ["proto_ordering.cc"],
    hdrs = ["proto_ordering.h"],
    deps = [
        ":proto",
        "@abseil-cpp//absl/algorithm:container",
        "@protobuf",
    ],
)

cc_library(
    name = "timer",
    hdrs = ["timer.h"],
    deps = ["@abseil-cpp//absl/time"],
)

cc_test(
    name = "proto_ordering_test",
    srcs = ["proto_ordering_test.cc"],
    deps = [
        ":proto_matchers",
        ":proto_ordering",
        ":proto_test_cc_proto",
        ":testing",
        "@googletest//:gtest_main",
        "@protobuf",
    ],
)

cc_test(
    name = "test_artifact_writer_test",
    srcs = ["test_artifact_writer_test.cc"],
    deps = [
        ":status_matchers",
        ":test_artifact_writer",
        ":test_artifact_writer_test_cc_proto",
        "@googletest//:gtest_main",
        # This dependency is not technically needed inside Google3,
        # but is a hack to keep the Copybara rules simple.
        "@google_benchmark//:benchmark",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "timer_test",
    srcs = ["timer_test.cc"],
    deps = [
        ":timer",
        "@abseil-cpp//absl/time",
        "@googletest//:gtest_main",
    ],
)

bzl_library(
    name = "diff_test_bzl",
    srcs = ["diff_test.bzl"],
    parse_tests = False,
)
