name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run daily at midnight to ensure we catch regressions.
    - cron: "0 0 * * *"
  # Allow manual triggering of the workflow.
  # https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bazel_version: [7.x, latest]

    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel_version }}

    steps:
      - uses: actions/checkout@v6

      - name: Mount bazel cache
        uses: actions/cache/restore@v5
        with:
          path: ~/.cache/bazel
          key: bazel-${{ matrix.bazel_version }}-${{ hashFiles('**/*.bazel*', '**/*.bzl') }}
          restore-keys: |
            bazel-${{ matrix.bazel_version }}-

      - name: Save start time
        run: echo "START_TIME=$(date +%s)" >> "$GITHUB_ENV"

      - name: Build
        run: bazel build --test_output=errors //...
      - name: Test
        run: bazel test --test_output=errors //...

      - name: Calculate build duration
        if: always()
        run: echo "duration=$(( $(date +%s) - START_TIME ))" >> "$GITHUB_ENV"

      - name: Compress cache
        if: always()
        run: rm -rf $(bazel info repository_cache)

      - name: Save bazel cache
        uses: actions/cache/save@v4
        # Only create a new cache entry if we're on the main branch or the build takes >5mins.
        #
        # NOTE: Even though `always()` evaluates to true, and `true && x == x`, the `always() &&`
        # prefix is not redundant! The call to `always()` has a side effect, which is to override
        # the default behavior of automagically canceling this step if a previous step failed.
        # (Don't blame me, blame GitHub Actions!)
        if: always() && (github.ref_name == 'main' || env.duration > 300)
        with:
          path: "~/.cache/bazel"
          key: bazel-${{ matrix.bazel_version }}-${{ hashFiles('**/*.bazel*', '**/*.bzl') }}-${{ github.run_id }}
